//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "FullName")]
        public string FullName { get; set; }
        [Display(Name = "AdminEmail")]
        [DataType(DataType.EmailAddress)]
        public string AdminEmail { get; set; }
        [Display(Name = "UserName")]
        public string UserName { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public System.DateTime updationDate { get; set; }
    }
}
